name: LaTeX release

on:
  push:
    tags:
      - "*"
  pull_request:
    branches:
      - dev
    types:
      - opened
      - edited

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      # Build the PDF using latexmk command, with a high level of verbosity
      - name: Build PDF
        uses: xu-cheng/texlive-action/full@v1 # https://github.com/xu-cheng/texlive-action
        with:
          run: |
            latexmk -verbose
            echo github.event_name

      # Create a release that contains the generated PDF, named according to the name of the t
      - name: Create release
        uses: svenstaro/upload-release-action@v2 # https://github.com/svenstaro/upload-release-action
        if: ${{ success() }} && !contains(github.event_name, "push") # if successs and it's not a push
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: output/TemplateLatex.pdf # Add the file to the asset of the release
          asset_name: TemplateLaTeX-$tag.pdf
          tag: ${{ github.ref }}
          overwrite: true
