name: LaTeX release

on:
  push:
    tags:
      - "*"
  pull_request:
    branches:
      - dev
    types:
      - opened
      - edited

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      # Build the PDF using latexmk command, with a high level of verbosity
      - name: Build PDF
        uses: xu-cheng/texlive-action/full@v1 # https://github.com/xu-cheng/texlive-action
        with:
          run: |
            latexmk -verbose
            echo github.event_name

      # Create a release that contains the generated PDF, named according to the name of the tag
      # The release is created only if the trigger is a pushed tag
      - name: Create release
        uses: svenstaro/upload-release-action@v2 # https://github.com/svenstaro/upload-release-action
        if: startsWith(github.ref, 'refs/tags/') # if success and it's pushed tag
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: output/**/*
          file_glob: true
          tag: ${{ github.ref }}

